//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tatu_companyEntities : DbContext
    {
        public tatu_companyEntities()
            : base("name=tatu_companyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<boleta> boleta { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<comuna> comuna { get; set; }
        public DbSet<sucursal> sucursal { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tatuador> tatuador { get; set; }
        public DbSet<tatuaje> tatuaje { get; set; }
        public DbSet<venta> venta { get; set; }
    }
}
