//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tatu_company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venta()
        {
            this.boleta = new HashSet<boleta>();
        }
    
        public int id_venta { get; set; }
        public int id_cliente { get; set; }
        public int id_tatuador { get; set; }
        public int id_sucursal { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public int id_tatuaje { get; set; }
        public int valor_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual tatuador tatuador { get; set; }
        public virtual tatuaje tatuaje { get; set; }
    }
}
